Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }
        [Required(ErrorMessage = "Kullanıcı Adı zorunludur.")]
        public string? UserName { get; set; }
        [Required(ErrorMessage = "Kullanıcı Soyadı zorunludur.")]
        public string? UserSurname{get; set; }

        public string? UserAd
        {
            get
            {

                return UserName+" "+UserSurname;
            }
        }

        public List<Book> Books { get; set; } = new List<Book>();


       


    }
}

Controllers/BookController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookApp.Controllers
{
    public class BookController:Controller
    {
        public readonly DataContext _context;
        public BookController(DataContext context) //Bu işemlere Injection deniyor.
        {
            _context = context;
        }
      
        public IActionResult Create(int? Id)
        {
            if (Id == null)
            {
                ViewBag.Users = new SelectList(_context.Users, "UserId", "UserName");

                return View();
            }

            // Kullanıcı bilgisini çekiyoruz
            var user = _context.Users.Find(Id);
            if (user == null)
            {
                return NotFound();
            }

            
            var book = new BookViewModel//Model olarak bunu alıyor.
            {
                UserId = user.UserId
            };

            
            ViewBag.Users = new SelectList(_context.Users, "UserId", "UserName");

            return View(book);
        }


        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel model)//Kitap bilgileri geleceği için Bu şekilde 
        {//asenkron sıra alınır yemek gelince verilir senkronda kişinin yemeğei gelmeden başka sipariş alınmaz
    
            if (ModelState.IsValid)
            {
                _context.Books.Add(new Book() { BookId = model.BookId, BookName = model.BookName, AuthorName = model.AuthorName,
                    PublisherName = model.PublisherName, PublisherYear = model.PublisherYear ,UserId=model.UserId });
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            ViewBag.Users = new SelectList(await _context.Users.ToListAsync(), "UserId", "UserName");
            return View(model);


        }

        public async Task<IActionResult> Index(string searchString, string author)
        {
      

            var books = _context.Books.Include(b => b.Users).AsQueryable(); // IQueryable olarak başlatıyoruz

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.searchString = searchString;
                books = books.Where(b => b.BookName.ToLower().Contains(searchString.ToLower())); // Veritabanı üzerinde filtreleme
            }

            if (!String.IsNullOrEmpty(author)&& author!="0")
            {
                books = books.Where(b => b.BookId == int.Parse(author));//b.bookid ile tüm satırları kontrol edip filtreleme işlemi
            }


            ViewBag.Books=new SelectList(_context.Books, "BookId","AuthorName");

            var bookList = await books.ToListAsync(); // Veritabanına sorguyu yapıp listeyi alıyoruz.

            return View(bookList);
        }
        


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }


            var book = await _context

                .Books
                .Include(u => u.Users) //Buna bile gerek yok
                                      .Select(u=>new BookViewModel //Normal book da kullanabiliriz
                                      { 
                                         BookId=u.BookId, BookName=u.BookName,AuthorName=u.AuthorName,PublisherName=u.PublisherName,PublisherYear=u.PublisherYear,UserId=u.UserId 
                                       })                                                                                //Bu şekilde  istediğimiz bilgileri 

                  .FirstOrDefaultAsync(u => u.BookId == id);


            if (book == null)
            {
                return NotFound();
            }
            ViewBag.Users = new SelectList(await _context.Users.ToListAsync(), "UserId", "UserName");
            return View(book);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, BookViewModel model)//Burası Kurs di
        {
            if (id != model.BookId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Books.Update(new Book() { BookId = model.BookId, BookName = model.BookName, AuthorName = model.AuthorName, PublisherName = model.PublisherName, PublisherYear = model.PublisherYear, UserId = model.UserId });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException)
                {                       // o nesnesi veri tabını tarıyor moddelin id sine bakıyor.
                    if (!_context.Books.Any(o => o.BookId == model.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.Books = new SelectList(await _context.Books.ToListAsync(), "OgretmenId", "AdSoyad");
            return View(model);
        }

       public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);


            if(book==null)
            {
                return NotFound();
            }

            return View(book);

        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int BookId)//asp-for ile de @Model.BookId gönderip iki parametre olaiblir
        {
            if (BookId == null)
            {
                return NotFound();

            }
            var book = await _context.Books.FindAsync(BookId);
            if (book == null)
            {
                return NotFound();
            }
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {

            if(id == null)
            {
                return NotFound();
            }

            var book= await _context
                .Books
                .Include(b=>b.Users)
                .FirstOrDefaultAsync(u => u.BookId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);


        }







    }
}

Controllers/UserController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookApp.Controllers
{
    public class UserController :Controller
    {
         public readonly DataContext _context;//yapıcı metot içine 
        public UserController(DataContext context) //Bu işemlere Injection deniyor.
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }   
        [HttpPost]

        public async Task<IActionResult> Create(User model)//User bilgileri geleceği için Bu şekilde 
        {//asenkron sıra alınır yemekgelince verilir senkronda kişinin yemeğei gelmeden başka sipariş alınmaz
            if (ModelState.IsValid)
            {
                _context.Users.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);

        }

        public async Task<IActionResult> Index()
        {
            var user = await _context.Users.ToListAsync();

            return View(user);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserId == id);

            if (user == null)
            {

                return NotFound();

            }
            return View(user);

        }
        [HttpPost]
        
        public async Task<IActionResult> Edit(int? id, User model)
        {
            if (id != model.UserId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Users.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {                       // o nesnesi veri tabını tarıyor moddelin id sine bakıyor.
                    if (!_context.Users.Any(u => u.UserId == model.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int UserId)
        {
            if (UserId <= 0)
            {
                return NotFound();
            }

            var user = await _context.Users
           .Include(u => u.Books) // Kullanıcının kitaplarını da çek
           .FirstOrDefaultAsync(u => u.UserId == UserId);
            if (user == null)
            {
                return NotFound();
            }

            
            //var userBooks = _context.Books.Where(b => b.UserId == UserId).ToList();

            
            _context.Books.RemoveRange(user.Books);

            // Kullanıcıyı kaldır
            _context.Users.Remove(user);

            // Veritabanına değişiklikleri kaydet
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(i => i.Books)
                .FirstOrDefaultAsync(i => i.UserId == id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }






    }




}


    

Views/User/Create.cshtml
@model User

<h2>Kullanıcı Ekle</h2>
<br />

<form asp-controller="User" asp-action="Create" method="post">
	<div asp-validation-summary="All"></div>
	<div class="mb-3">
		<label asp-for="UserName" class="form-label">Kullanıcı Adı</label>
		<input asp-for="UserName" class="form-control">
		<span asp-validation-for="UserName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="UserSurname" class="form-label">Kullanıcı Soyadı</label>
		<input asp-for="UserSurname" class="form-control">
		<span asp-validation-for="UserSurname" class="text-danger"></span>
	</div>
	
	<button class="btn btn-primary" type="submit" >Kaydet</button>

</form>

Views/User/Delete.cshtml
@model User

<div class="container d-flex justify-content-center">
    <div class="card mt-0" style="width: 18rem;">
        <div class="card-body text-center">
            <h5 class="card-title">Uyarı Mesajı</h5>
            <p class="card-text">
                @Model.UserName    isimli Kullanıcıyı ve Kitaplarını silmek istiyor musunuz?
            </p>
            <form asp-action="Delete" method="post">
                <input type="hidden" value="@Model.UserId" name="UserId" />
                <button class="btn btn-danger" type="submit">Evet</button>
                <a asp-action="Index" class="btn btn-primary">Hayır</a>
            </form>
        </div>
    </div>
</div>

	






	

Views/User/Details.cshtml
@model User

<h2>Kitap Listesi</h2>
<br />
<a href="/Book/Create" class="btn btn-primary">Kitap Ekle</a>

<table class="table mt-3 table-striped table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th scope="col">Kitap ID</th>
            <th scope="col">Kitap Adı</th>
            <th scope="col">Yazar Adı</th>
         
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model?.Books) // Eğer null ise boş liste döndür
        {
            <tr>
                <td>@book.BookId</td>
                <td>
                    <a asp-controller="Book" asp-action="Details" asp-route-id="@book.BookId" class="text-primary text-decoration-none table-hover">
                        @book.BookName
                    </a>
                </td>
                <td>@book.AuthorName</td>
       

            </tr>
        }
    </tbody>
</table>

Views/User/Edit.cshtml
@model User

<h2>Kullanıcı Ekle</h2>
<br />

<form asp-controller="User" asp-action="Edit" method="post">
	<input type="hidden" asp-for="UserId" />

	<div class="mb-3">
		<label asp-for="UserName" class="form-label">Kullanıcı Adı</label>
		<input asp-for="UserName" class="form-control">
		<span asp-validation-for="UserName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="UserSurname" class="form-label">Kullanıcı Soyadı</label>
		<input asp-for="UserSurname" class="form-control">
		<span asp-validation-for="UserSurname" class="text-danger"></span>
	</div>

	<button class="btn btn-primary" type="submit">Kaydet</button>

</form>

Views/User/Index.cshtml
@model List<User>

<h2>Kullanıcı Listesi</h2>
<br />
<a href="/User/Create" class="btn btn-primary">Kullanıcı Ekle</a>
<table class="table">
	<thead>
		<tr>
			<td>Kullanıcı ID</td>     <!--Html.DisplayNameFor(m => m.UserName)-->
			<td>Kullanıcı Adı</td>
			<td>Kullanıcı Soyadı</td>
			<td></td>
			<td></td>

		</tr>
	</thead>
	<tbody>
		@foreach (var user in Model)
		{
			<tr>
				<td>@user.UserId</td>  <!-- Burada Displayde olutyorö-->
			<td>	
				<a asp-controller="User" asp-action="Details" asp-route-id="@user.UserId" class="text-primary text-decoration-none table-hover">
					@user.UserName
					</a>
				</td>
				<td>@user.UserSurname</td>
				<td>
					<a asp-controller="User" asp-action="Edit" asp-route-id="@user.UserId" class="btn btn-sm btn-danger">Düzenle</a>
					<a asp-controller="User" asp-action="Delete" asp-route-id="@user.UserId" class="btn btn-sm btn-danger">Sil</a>

				</td>
				<td><a asp-controller="Book" asp-action="Create" asp-route-id="@user.UserId" class="btn btn-sm btn-danger">Kitap Ekle</a></td>

			</tr>

		}

	</tbody>


</table>